In [54]:
import time
import numpy as np
import rlgym_sim

TPS = 120 / 8

from utils import build_rocketsim_env

env = build_rocketsim_env(name="visgym", phase=1)

In [68]:
obs = env.reset()
# obs

In [84]:
env._match.agents

2

In [92]:
action = env.action_space.sample()
action

array([2, 1, 1, 2, 0, 0, 1, 0], dtype=int64)

In [93]:
# double the length of action:
baction = np.vstack([action, action])
# baction = np.concatenate([action, action])
print(baction)

[[2 1 1 2 0 0 1 0]
 [2 1 1 2 0 0 1 0]]


In [95]:
env.step(baction)

([array([-3.01049680e-01, -6.42075358e-01,  4.07362876e-01,  2.84537852e-01,
         -6.26435354e-02, -2.55741388e-01,  1.40034243e-01,  2.93554336e-01,
         -3.63054425e-01,  1.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          1.00000000e+00, -1.00000000e+00,  0.00000000e+00,  1.00000000e+00,
          0.00000000e+00,  1.00000000e+00,  1.00000000e+00,  1.00000000e+00,
          1.00000000e+00,  1.00000000e+00,  1.00000000e+00,  1.00000000e+00,
          1.00000000e+00,  1.00000000e+00,  1.00000000e+00,  1.00000000e+00,
          1.00000000e+00,  1.00000000e+00,  1.00000000e+00,  1.00000000e+00,
          1.00000000e+00,  1.00000000e+00,  1.00000000e+00,  1.00000000e+00,
          1.00000000e+00,  1.00000000e+00,  1.00000000e+00,  1.00000000e+00,
          1.00000000e+00,  1.00000000e+00,  1.00000000e+00,  1.00000000e+00,
          1.00000000e+00,  1.00000000e+00,  1.00000000e+00,  1.00000000e+00,
          1.00000000e+00,  1.00000000e+00,  1.00000000e+00,  5.27747929e-01,